In [1]:
🔵 What is NumPy?

NumPy (Numerical Python) is a Python library designed for working with numerical data and performing mathematical operations efficiently.

Think of it as a powerful tool for handling arrays, matrices, and large amounts of numerical data.

✅ Advantages of NumPy
Fast
NumPy performs numerical calculations much faster than normal Python lists.
It is especially useful when working with large datasets.
Efficient memory usage
NumPy arrays generally use memory more efficiently than Python lists.
Easy mathematical operations
You can perform mathematical calculations on entire arrays efficiently.
Supports multidimensional data
It can work with 1D, 2D, 3D, and higher-dimensional arrays.
Many built-in functions
Provides functions for statistics, mathematics, linear algebra, random numbers, etc.
Foundation for Data Science
Many Python libraries used in Data Science and Machine Learning work with NumPy or are built around similar array concepts.
🎯 Benefits of NumPy

The main benefits are:

⚡ Faster numerical calculations
💾 Better memory efficiency
📊 Easy handling of numerical datasets
🧮 Powerful mathematical operations
📐 Matrix and linear algebra support
🎲 Random number generation
🤖 Useful for Machine Learning
📈 Useful for Data Science
🔗 Works well with other Python libraries
🔧 Uses of NumPy

NumPy is commonly used for:

1. Data Science

Working with and processing numerical datasets.

2. Machine Learning

Preparing numerical data and performing mathematical operations required by ML algorithms.

3. Artificial Intelligence

Many AI operations involve large amounts of numerical data.

4. Scientific Computing

Used for scientific and engineering calculations.

5. Statistics

Calculating things such as mean, median, standard deviation, etc.

6. Linear Algebra

Working with vectors, matrices, matrix multiplication, and related operations.

7. Image Processing

Images can be represented as numerical arrays, so NumPy can be used to manipulate image data.

8. Simulations

Useful for generating and processing numerical data for simulations.

❌ Disadvantages of NumPy

NumPy is powerful, but it has some limitations:

Mainly designed for numerical data
It isn't as flexible as normal Python lists for storing completely different types of objects.
Requires learning
Arrays, dimensions, shapes, indexing, broadcasting, etc., can initially be confusing.
Not ideal for every type of data
For tabular data with columns of different types, Pandas is usually more convenient.
Memory considerations
Although NumPy is memory-efficient compared with Python lists in many cases, very large arrays can still consume significant memory.
Less suitable for general-purpose programming
NumPy is specifically focused on numerical/scientific computing rather than replacing Python's normal data structures.




[1 2 3 4 5 6]


In [ ]:
#Syntax of Numpy
import numpy as np
arr_syn = np.array([1,2,3,4,5,6])
print(arr_syn)


In [ ]:
Types of arrays dimensions:
    1.1d array
    2.2d array
    3.2d array
    

In [8]:
#1d array:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

#2d array:
arr_2d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr_2d)

#Multidimesional array:
arr_multi = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(arr_multi)

[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [ ]:
Creating different arrays
1.With default values for specific situation
2.np.zeros(shape),np.ones(),np.full(),np.arange(),np.eye()


In [18]:
import numpy as np
arr = np.zeros((3,3))
print(arr)

arr_one = np.ones((2,2))
print(arr_one)

arr_arrange = np.arange(1,10,2)
print(arr_arrange)

arr_i = np.eye(3,3)
print(arr_i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#Pratice questions

#1
import numpy as np
arr_1 = np.array([10,20,30,40,50])
print(arr_1)

#2
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr_2d)

#3
arr_zero = np.zeros(5)
print(arr_zero)

#4
arr_one = np.ones(7)
print(arr_one)

#5
arr_range = np.arange(10,20)
print(arr_range)

#6
arr_1range = np.arange(0,20,2)
print(arr_1range)

[10 20 30 40 50]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
#Array Properties & Operations:
Prperties:
1.ndim - number of dimentions
2.shape - To check the shape of the array
3.size - To check the how many values in array
4.dtype - To check the type of array
5.astype - To convert the type to another type (ex.int to float)

Opperations:
'+','-','*','/','//','**'
Comparsion operations:
'<','>','=','==','<=','>='
Aggregation functions:
[np.mean,np.max,np.min,np.sum,np.std,np.var]



SyntaxError: invalid decimal literal (2584068251.py, line 3)

In [22]:
#Syntaxs one by one and pratice:

#ndim
import numpy as np
arr_one = np.array([1,2,3,4])
arr_two = np.array([[1,2,3,4],[5,6,7,8]])
arr_three = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(arr_one.ndim)
print(arr_two.ndim)
print(arr_three.ndim)
#size
print(arr_three.size)
#shape
print(arr_three.shape)
#dtype
print(arr_three.dtype)
#astype
type = arr_three.astype(float)

print(type)
print(type.dtype)

#Operations:
print(arr_three + 5)

print(arr_one + arr_two)

print(arr_one<3)
print(arr_one==4)

#Aggragations
print(arr_one.sum())
print(arr_one.min())
print(arr_one.max())
print(arr_one.std())
print(arr_one.var())
print(arr_one.round())


1
2
2
20
(5, 4)
int32
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]]
float64
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[ 2  4  6  8]
 [ 6  8 10 12]]
[ True  True False False]
[False False False  True]
10
1
4
1.118033988749895
1.25
[1 2 3 4]


AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [47]:
#Indexing and slicing

import numpy as np
arr_ind = np.array([1,2,3,4,1,3,4,5])

print(arr_ind[0:7:2])
print(arr_ind[arr_ind>0])


[1 3 1 4]
[1 2 3 4 1 3 4 5]


In [19]:
#Reshaping and manipulation
#reshape() changes the structure of an array
import numpy as np
arr_reshape = np.array([1,2,3,4,4,5])
print(arr_reshape.reshape(3,-1))
print(arr_reshape.reshape(2,3))

#Ravel and Flatten
arr_faltten = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_faltten)
#Ravel is used to return view
print(arr_faltten.ravel())
#Flatten is used copy the original one
print(arr_faltten.flatten())

#Concatenate : To combine two dimssions in one line like merging the two dim
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
con = np.concatenate((a,b))
print(con)

#Horizontal and Vertical : This two where used to convert the directions of any dim in vertical or Horizontal
vertical = np.vstack((a,b))
print(vertical)

Horizontal = np.hstack((a,b))
print(vertical)

[[1 2]
 [3 4]
 [4 5]]
[[1 2 3]
 [4 4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 5 6 7 8 9]
[1 2 3 4 5 5 6 7 8 9]


In [32]:
#Array Modifications
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
#1. Changing an Existing Element
arr[2] = 100
print(arr)

#2. Changing Multiple Elements
arr[2:3] = 30
print(arr)

#3. Conditional Modification
arr[arr<30]= 30
print(arr)

#4.append()
new_arr = np.append(arr,60)
print(new_arr)
#Multiple append
new_arrr = np.append(arr,[30,40,50])
print(new_arrr)

#5.Insert
new_insert = np.insert(arr,1,20)
print(new_insert)

#6.Delete
new_delete = np.delete(arr,1)
print(new_delete)


[ 10  20 100  40  50]
[10 20 30 40 50]
[30 30 30 40 50]
[30 30 30 40 50 60]
[30 30 30 40 50 30 40 50]
[30 20 30 30 40 50]
[30 30 40 50]


In [36]:
#Broadcasting & Vectorisation
#Vectorisation means performing an operation on an entire NumPy array at once instead of manually processing each element one by one.
import numpy as np
arr = np.array([1,2,3,4,5,6])
sum = arr * 3
print(sum)

'''
🧠 Why is Vectorisation useful?
Without vectorisation

You would typically need a loop to process every value.

With vectorisation

You perform the operation directly on the array.

Benefits:

⚡ Faster calculations
🧹 Cleaner code
📊 Good for large numerical datasets
🤖 Very useful in Machine Learning
🔢 Efficient mathematical operations


'''

#Broadcasting allows NumPy to perform operations between arrays with different shapes when their dimensions are compatible.
arr = np.array([10, 20, 30, 40])

arr_1 = np.array([[10,20,30,40],[20,30,40,50]])

result = arr + arr_1

print(result)

'''
⭐ Broadcasting Rules

This is the part you should understand carefully.

NumPy compares dimensions from right to left.

Two dimensions are compatible when:

Rule 1

They are the same size.

Example:

3
3

Compatible ✅

Rule 2

One of the dimensions is 1.

Example:

3
1

Compatible ✅

Rule 3

A missing dimension can be treated as 1.

❌ When Broadcasting Doesn't Work

Consider:

Array A → (2, 3)

Array B → (2,)

Let's compare from the right:

A:  2  3
B:     2

Compare:

3 vs 2

They're different and neither is 1.

So they aren't compatible ❌.

This produces a broadcasting error.

🟢 Practical Example: Adding a Constant

Suppose you have student marks:

[50, 60, 70, 80]

You want to give everyone 5 bonus marks.

Broadcasting allows you to add 5 to the entire array:

marks = np.array([50, 60, 70, 80])

new_marks = marks + 5

print(new_marks)

Result:

[55 65 75 85]
🟢 Vectorisation vs Broadcasting

This is important because they're related but not the same thing.

Vectorisation

Performing operations on an entire array efficiently.

Example:

array × 2

Broadcasting

Automatically adjusting compatible arrays/shapes so operations can happen between them.

Example:

2D array + 1D array

🧠 Easy memory trick

Vectorisation = HOW the operation is performed

Broadcasting = HOW different shapes work together

'''

[ 3  6  9 12 15 18]
[[20 40 60 80]
 [30 50 70 90]]


In [ ]:
#Handling Missing Values in NumPy
'''
Missing values are extremely common when working with real-world data.

For example, imagine a dataset of student marks:

Student     Marks
A           85
B           72
C           ?
D           91

The ? means the value is missing.

In NumPy, the most common representation for a missing numerical value is NaN.
'''
'''
1. What is NaN?

NaN = Not a Number

It represents a value that is missing or undefined.

For example:

arr = np.array([10, 20, np.nan, 40, 50])

print(arr)

You'll see:

[10. 20. nan 40. 50.]

Notice something interesting:

The integers became floating-point values.

That's because NaN is generally associated with floating-point numerical data.

2. Checking for Missing Values

NumPy provides:

np.isnan(arr)

This checks every element.

Conceptually:

10  → False
20  → False
NaN → True
40  → False
50  → False

So you'll get a Boolean array.

🧠 Remember

np.isnan() → checks whether a value is NaN

3. Finding How Many Missing Values

You can combine isnan() with sum():

np.isnan(arr).sum()

If your array contains one NaN, the result is:

1

Why?

Because:

True  = 1
False = 0

So counting True values gives the number of missing values.

4. Finding Non-Missing Values

You can use:

~np.isnan(arr)

The ~ means NOT.

So:

np.isnan(arr)

False False True False False

After ~:

True True False True True

This can be used to select values that aren't missing.

5. Removing NaN Values

NumPy provides:

arr[~np.isnan(arr)]

This selects only the values that are not NaN.

For:

[10, 20, NaN, 40, 50]

you get:

[10, 20, 40, 50]
'''